version: '3.8'

services:
  bot:
    build: .
    container_name: finance_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./app/database:/app/app/database
      - ./bot_log.log:/app/bot_log.log
      - ./subs.json:/app/subs.json
      - ./debts.json:/app/debts.json
      - ./cat_map.json:/app/cat_map.json
    environment:
      - TZ=Europe/Moscow